parameters:
  - name: vmImages
    type: object
  - name: nodeVersions
    type: object

stages:
  - template: ../stages/helper-deps-ci-skip.azure-pipelines.yml
    parameters:
      stages:
        - template: ../stages/node-test.azure-pipelines.yml
          parameters:
            vmImages: ${{ parameters.vmImages }}
            nodeVersions: ${{ parameters.nodeVersions }}
