name: $(Build.DefinitionName)_$(SourceBranchName)_$(BuildID)

variables:
  - group: azure-devops

pool:
  vmImage: 'ubuntu-latest'

steps:
  - pwsh: |
      git config user.name $env:AZUREDEVOPS_GITNAME; if (-not $?) { throw }
      git config user.email $env:AZUREDEVOPS_GITEMAIL; if (-not $?) { throw }
      git checkout main; if (-not $?) { throw }
      Copy-Item -Path src -Destination dist/release -Recurse
      git add --all
      git commit --message "Release: Automated release"; if (-not $?) { throw }
      git push https://$env:GitPat@dev.azure.com/cpuabuse/cpuabuse-public/_git/pipelines --force; if (-not $?) { throw }
    env:
      GitPat: $(AzureDevOps.GitPat)
