parameters:
  - name: pipeline
    type: string

extends:
  template: pipelines/${{ parameters.pipeline }}.azure-pipelines.yml
  parameters:
    vmImages:
      - ubuntu-latest
      - windows-latest
      - macOS-latest
    nodeVersions:
      - "15.4" # 15.6 bugs with npm publish
      - "12.x"
      - "14.x"
