parameters:
  - name: pipeline
    type: string

extends:
  template: pipelines/${{ parameters.pipeline }}.azure-pipelines.yml
  parameters:
    vmImages:
      - ubuntu-latest
      - windows-latest
      - macOS-latest
    nodeVersions:
      - "20.x"
      - "18.x"
      - "16.x"
      - "14.x"
